/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;
import classes.NNatural;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edivan
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_segundoNumero = new javax.swing.JTextField();
        jButton_Executar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_PrimeiroNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_NNatural = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NÚMEROS NATURAIS");

        jLabel2.setText("PRIMEIRO NÚMERO");

        jButton_Executar.setText("EXECUTAR");
        jButton_Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExecutarActionPerformed(evt);
            }
        });

        jLabel3.setText("SEGUNDO NÚMERO");

        jTable_NNatural.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Itens", "PRIMEIRO", "SEGUNDO"
            }
        ));
        jScrollPane1.setViewportView(jTable_NNatural);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Executar)
                        .addGap(220, 220, 220))))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_PrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_PrimeiroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_segundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Executar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecutarActionPerformed
        // TODO add your handling code here:
        try {
            
            //iram pegar o valor da tela 1° jeito
            NNatural quarto = new NNatural(Long.parseLong(jTextField_PrimeiroNumero.getText()));
            //* ou 2° jeito  "formas de fazer a mesma coisa"**/

            // esse de baixo esta errado tem que ver oque esta de errado;            
            Long valor1 = Long.parseLong(jTextField_PrimeiroNumero.getText());
            NNatural terceiro = new NNatural(valor1);

            // 3° jeito ; formas diferentes de pegar os valores.     
            Long valor = Long.parseLong(jTextField_PrimeiroNumero.getText());
            NNatural primeiro = new NNatural();
            primeiro.setNumero(valor);

            valor = Long.parseLong(jTextField_segundoNumero.getText());
            NNatural segundo = new NNatural();
            segundo.setNumero(valor);

            long objeto = Long.parseLong(jTextField_segundoNumero.getText());
            NNatural quinto = new NNatural();
            quinto.setNumero(objeto);

            objeto = Long.parseLong(jTextField_segundoNumero.getText());
            NNatural sexto = new NNatural();
            sexto.setNumero(objeto);
            /*
             DefaultTableModel model = (DefaultTableModel) jTable_NNatural.getModel();
             // Adicionando Matriz e addicionando sas linhas
             String [] linha = new String[]{"QUADRADO PERFEITO","SIM","NÃO"};
             model.addRow(linha);
             // Exemplo 2;
             linha = new String []{"teste1", "teste2", "teste3"};
             model.addRow(linha);
             
             linha = new String []{"teste4", "teste4", "teste4"};
             model.addRow(linha);
             */
            // OUTRA FORMA DE FAZER ---------
            DefaultTableModel model = (DefaultTableModel) jTable_NNatural.getModel();
            // Adicionando Matriz e addicionando as linhas

            // NUMERO PERFEITO
            String[] linha3 = new String[3];
            linha3[0] = "NÚMERO PERFEITO";
            if (primeiro.nPerfeito()) {
                linha3[1] = "sim";
            } else {
                linha3[1] = "não";
            }

            if (segundo.nPerfeito()) {
                linha3[2] = "sim";
            } else {
                linha3[2] = "não";
            }

            model.addRow(linha3);

            String[] linha = new String[3];
            linha[0] = "QUADRADO PERFEITO";
            if (primeiro.eQuadradoPerfeito()) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.eQuadradoPerfeito()) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            // Número fatorial
            linha[0] = "NUMERO FATORIAL";
            linha[1] = " " + primeiro.fatorial();
            linha[2] = " " + segundo.fatorial();
            model.addRow(linha);

            linha[0] = "NÚMERO CAPICUA";
            if (primeiro.capicua()) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.capicua()) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            linha[0] = "NÚMERO PRIMOS";
            if (primeiro.primos()) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.primos()) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

//             // BASE 2, NÚMERO BINARIO  - Fincionando - ok
//            linha[0] = "BASE 2";
//            linha[1] = " " + primeiro.base2();
//            linha[2] = " " + segundo.base2();
//            model.addRow(linha);
//            
//            // Base 8 - Octal
//            linha[0] = "BASE 8";
//            linha[1] = " " + primeiro.base8();
//            linha[2] = " " + segundo.base8();
//            model.addRow(linha);
//             
//            // BASE 16
//            linha[0] = "NÚMERO BASE 16";
//            linha[1] = " " + primeiro.base16();
//            linha[2] = " " + segundo.base16();
//            model.addRow(linha);
//          ou jeito usando o scwit case 
            // BASE 2, NÚMERO BINARIO - Rogerio ------ linha 187
            linha[0] = "BASE 2";
            linha[1] = " " + primeiro.MudarBase(2);
            linha[2] = " " + segundo.MudarBase(2);
            model.addRow(linha);

            // Base 8 - Octal
            linha[0] = "BASE 8";
            linha[1] = " " + primeiro.MudarBase(8);
            linha[2] = " " + segundo.MudarBase(8);
            model.addRow(linha);

            // BASE 16
            linha[0] = "NÚMERO BASE 16";
            linha[1] = " " + primeiro.MudarBase(16);
            linha[2] = " " + segundo.MudarBase(16);
            model.addRow(linha);

            // MDC teste de mesa
            linha[0] = "NÚMERO MDC";
            linha[1] = " " + primeiro.mdc(segundo).getNumero();
            linha[2] = " " + segundo.mdc(primeiro).getNumero();
            model.addRow(linha);

            linha[0] = "NÚMERO MMC";
            linha[1] = " " + primeiro.mmc(segundo).getNumero();
            linha[2] = " " + segundo.mmc(primeiro).getNumero();
            model.addRow(linha);

            linha[0] = "PRIMOS ENTRE SI";
            if (primeiro.saoPrimos(segundo)) {
                linha[1] = " SIM ";
            } else {
                linha[1] = "NÃO";
            }

            if (primeiro.saoPrimos(segundo)) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro);
        }


    }//GEN-LAST:event_jButton_ExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_NNatural;
    private javax.swing.JTextField jTextField_PrimeiroNumero;
    private javax.swing.JTextField jTextField_segundoNumero;
    // End of variables declaration//GEN-END:variables
}
